In [2]:
def my_function():
    pass

In [3]:
def my_sq(x):
    return x ** 2

In [4]:
my_sq(4)

16

In [5]:
my_sq("hello")

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [6]:
assert my_sq(4) == 16

In [7]:
assert my_sq(4) == 20

AssertionError: 

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    "a": [10, 20, 30],
    "b": [20, 30, 40]
})

In [10]:
df

a   b
0  10  20
1  20  30
2  30  40

In [11]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [12]:
my_sq(df["a"])

0    100
1    400
2    900
Name: a, dtype: int64

In [13]:
type(df["a"])

pandas.core.series.Series

In [14]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [15]:
my_sq

<function __main__.my_sq(x)>

In [16]:
def my_exp(x, e):
    return x ** e

In [17]:
my_exp(4, 2)

16

In [18]:
assert my_exp(10, 2) == 100

In [19]:
df["a"].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [20]:
def my_exp_flipped(e, x):
    return my_exp(x, e)

In [21]:
df["a"].apply(my_exp_flipped, x=10)

0                        10000000000
1              100000000000000000000
2    1000000000000000000000000000000
Name: a, dtype: object

In [22]:
df["a"].apply(lambda val: my_exp(x = val, e=10))

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [23]:
df["a"].apply(lambda val: my_exp(x = 10, e=val))

0                        10000000000
1              100000000000000000000
2    1000000000000000000000000000000
Name: a, dtype: object

In [24]:
def print_me(x):
    print(x)

In [25]:
print_me("daniel")

daniel


In [26]:
df["a"].apply(print_me)

10
20
30


0    None
1    None
2    None
Name: a, dtype: object

In [27]:
df

a   b
0  10  20
1  20  30
2  30  40

In [28]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [29]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [30]:
assert avg_3(0, 5, 10) == 5

In [31]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [32]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [33]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [34]:
df.apply(print_me, axis="columns")

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [35]:
df.apply(print_me, axis=1)

a    10
b    20
Name: 0, dtype: int64
a    20
b    30
Name: 1, dtype: int64
a    30
b    40
Name: 2, dtype: int64


0    None
1    None
2    None
dtype: object

In [36]:
df

a   b
0  10  20
1  20  30
2  30  40

In [37]:
def avg_2(x, y):
    return (x + y) / 2

In [38]:
(df["a"] + df["b"]) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [39]:
avg_2(df["a"], df["b"])

0    15.0
1    25.0
2    35.0
dtype: float64

In [40]:
import numpy as np

In [41]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [42]:
avg_2_mod(20, 10)

nan

In [43]:
avg_2_mod(0, 10)

5.0

In [44]:
avg_2_mod(df["a"], df["b"])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [46]:
import numpy as np

def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

avg_2_mod_np = np.vectorize(avg_2_mod)

In [47]:
avg_2_mod_np(20, 10)

array(nan)

In [48]:
avg_2_mod_np(0, 10)

array(5.)

In [49]:
avg_2_mod_np(df["a"], df["b"])

array([15., nan, 35.])

In [50]:
@np.vectorize
def avg_2_mod_np(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [51]:
avg_2_mod_np(df["a"], df["b"])

array([15., nan, 35.])

In [52]:
import numba

In [53]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [54]:
avg_2_mod_numba(df["a"], df["b"])

ValueError: Cannot determine Numba type of <class 'pandas.core.series.Series'>

In [55]:
type(df["a"])

pandas.core.series.Series

In [56]:
type(df["a"].values)

numpy.ndarray

In [57]:
df["a"].values

array([10, 20, 30], dtype=int64)

In [58]:
avg_2_mod_numba(df["a"].values, df["b"].values)

array([15., nan, 35.])

In [59]:
%%timeit
avg_2(df["a"], df["b"])

218 µs ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [60]:
%%timeit
avg_2_mod_np(df["a"], df["b"])

63.6 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
%%timeit
avg_2_mod_numba(df["a"].values, df["b"].values)

12.2 µs ± 491 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
